### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by HenryDev** [StartPolymer/progressive-web-app-template#19]
When I run `polymer init startpolymer` I get:
```
info:    Running template polymer-init-startpolymer:app...
error:   Template polymer-init-startpolymer:app not found
error:   cli runtime exception: Error: Template polymer-init-startpolymer:app not found
error:   Error: Template polymer-init-startpolymer:app not found
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/lib/init/init.js:241:19)
    at next (native)
    at fulfilled (/usr/local/lib/node_modules/polymer-cli/lib/init/init.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

```
and when I run local I'm missing bower components

**Comment by JosefJezek** [comment]
https://github.com/StartPolymer/progressive-web-app-template#setup

**Comment by HenryDev** [comment]
yes I did the steps in the setup, still got the same error.
